#ifndef UCHAOS_CONFIG_H 
#define UCHAOS_CONFIG_H

#define UCHAOS                           1

/* UCHAOS CONSOLE DEFS */
#define UCHAOS_CONSOLE_QUEUE_SIZE        5
#define UCHAOS_CONSOLE_QUEUE_ALIGN       4
#define UCHAOS_CONSOLE_MSG_SIZE          32
#define UCHAOS_CONSOLE_THREAD_STACKSIZE  512
#define UCHAOS_CONSOLE_THREAD_PRIORITY   10
#define UCHAOS_CONSOLE_THREAD_SLEEP      2000

/* UCHAOS SENSOR DEFS */
#define UCHAOS_SENSORS_NUMBER            2
#define UCHAOS_SENSOR_NAME_LEN           24

/* UCHAOS THREADS DEFS */
#define THREADS_NUMBER                   8

/* UCHAOS BATTERY DEFS */
#define BATTERY_INITIAL_VOLTAGE          3.3f
#define BATTERY_DEEP_DISCHARGE_VOLTAGE   2.0f

#define UCHAOS_FAULT_NAME_LEN            16

#endif